name: Crystal CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.0.0

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Validate formatting
      run: crystal tool format --check
    - name: Run tests
      run: make spec
    - name: Install specsuite dependencies
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19.4'
    - name: Download specsuite tests
      uses: actions/checkout@v3
      with:
        repository: hashicorp/hcl
        ref: v2.15.0
        path: go-hcl
    - name: Run specsuite
      env:
        SPECSUITE_TESTS: go-hcl/specsuite/tests
      run: make specsuite
