name: Crystal CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: 1.17
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: make spec
    - name: Validate formatting
      run: crystal tool format --check
