name: Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: 1.17
    - name: Install dependencies
      run: shards install
    - name: Generate docs
      run: crystal docs
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/master'
      with:
        allow_empty_commit: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
